//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripPoint.WindowsPhone.I18N {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TripPoint.WindowsPhone.I18N.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Notes.
        /// </summary>
        public static string AddNotes {
            get {
                return ResourceManager.GetString("AddNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Pictures.
        /// </summary>
        public static string AddPictures {
            get {
                return ResourceManager.GetString("AddPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to title.
        /// </summary>
        public static string AddPictureTitle {
            get {
                return ResourceManager.GetString("AddPictureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip Point.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string Cancel_AppBar {
            get {
                return ResourceManager.GetString("Cancel_AppBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new note.
        /// </summary>
        public static string CheckpointAddNotesViewTitle {
            get {
                return ResourceManager.GetString("CheckpointAddNotesViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new picture.
        /// </summary>
        public static string CheckpointAddPicturesViewTitle {
            get {
                return ResourceManager.GetString("CheckpointAddPicturesViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT CHECKPOINT.
        /// </summary>
        public static string CheckpointEditViewTitle {
            get {
                return ResourceManager.GetString("CheckpointEditViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkpoints.
        /// </summary>
        public static string Checkpoints {
            get {
                return ResourceManager.GetString("Checkpoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this checkpoint?.
        /// </summary>
        public static string ConfirmDeleteCheckpoint {
            get {
                return ResourceManager.GetString("ConfirmDeleteCheckpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this picture?.
        /// </summary>
        public static string ConfirmDeletePicture {
            get {
                return ResourceManager.GetString("ConfirmDeletePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this trip?.
        /// </summary>
        public static string ConfirmDeleteTrip {
            get {
                return ResourceManager.GetString("ConfirmDeleteTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to finish the trip?.
        /// </summary>
        public static string ConfirmFinishTrip {
            get {
                return ResourceManager.GetString("ConfirmFinishTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Checkpoint.
        /// </summary>
        public static string CreateCheckpoint {
            get {
                return ResourceManager.GetString("CreateCheckpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to checkpoint.
        /// </summary>
        public static string CreateCheckpoint_AppBar {
            get {
                return ResourceManager.GetString("CreateCheckpoint_AppBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new checkpoint.
        /// </summary>
        public static string CreateCheckpointViewTitle {
            get {
                return ResourceManager.GetString("CreateCheckpointViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trip.
        /// </summary>
        public static string CreateTrip_AppBar {
            get {
                return ResourceManager.GetString("CreateTrip_AppBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Trip.
        /// </summary>
        public static string CreateTripPageTitle {
            get {
                return ResourceManager.GetString("CreateTripPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Trip.
        /// </summary>
        public static string CurrentTrip {
            get {
                return ResourceManager.GetString("CurrentTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string Delete_AppBar {
            get {
                return ResourceManager.GetString("Delete_AppBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete....
        /// </summary>
        public static string Delete_AppBar_MenuItem {
            get {
                return ResourceManager.GetString("Delete_AppBar_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete checkpoint....
        /// </summary>
        public static string Delete_Checkpoint_AppBar {
            get {
                return ResourceManager.GetString("Delete_Checkpoint_AppBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete the trip. Restart the application and try again..
        /// </summary>
        public static string DeleteTripFailed {
            get {
                return ResourceManager.GetString("DeleteTripFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting.
        /// </summary>
        public static string Deleting {
            get {
                return ResourceManager.GetString("Deleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit.
        /// </summary>
        public static string Edit_AppBar {
            get {
                return ResourceManager.GetString("Edit_AppBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finding Your Location.
        /// </summary>
        public static string FindingYourLocation {
            get {
                return ResourceManager.GetString("FindingYourLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to finish trip.
        /// </summary>
        public static string FinishTrip_AppBar {
            get {
                return ResourceManager.GetString("FinishTrip_AppBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Checkpoint.
        /// </summary>
        public static string LatestCheckpoint {
            get {
                return ResourceManager.GetString("LatestCheckpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location not found.
        /// </summary>
        public static string LocationNotFoundCaption {
            get {
                return ResourceManager.GetString("LocationNotFoundCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application could not find your location. Please make sure location service is turned on.
        ///
        ///Would you like to save this checkpoint?.
        /// </summary>
        public static string LocationNotFoundText {
            get {
                return ResourceManager.GetString("LocationNotFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application does not have access to your location.
        /// </summary>
        public static string LocationServiceOffSettingDescription {
            get {
                return ResourceManager.GetString("LocationServiceOffSettingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application has access to your location.
        /// </summary>
        public static string LocationServiceOnSettingDescription {
            get {
                return ResourceManager.GetString("LocationServiceOnSettingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to past trips.
        /// </summary>
        public static string PastTrips_AppBar {
            get {
                return ResourceManager.GetString("PastTrips_AppBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to past trips.
        /// </summary>
        public static string PastTripsViewTitle {
            get {
                return ResourceManager.GetString("PastTripsViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pictures.
        /// </summary>
        public static string Pictures {
            get {
                return ResourceManager.GetString("Pictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string PrivacyPolicyLinkContent {
            get {
                return ResourceManager.GetString("PrivacyPolicyLinkContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to privacy policy.
        /// </summary>
        public static string PrivacyPolicyViewTitle {
            get {
                return ResourceManager.GetString("PrivacyPolicyViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string Save_AppBar {
            get {
                return ResourceManager.GetString("Save_AppBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving.
        /// </summary>
        public static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select.
        /// </summary>
        public static string Select_AppBar {
            get {
                return ResourceManager.GetString("Select_AppBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string Settings_AppBar {
            get {
                return ResourceManager.GetString("Settings_AppBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp.
        /// </summary>
        public static string Timestamp {
            get {
                return ResourceManager.GetString("Timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip Details.
        /// </summary>
        public static string TripDetails {
            get {
                return ResourceManager.GetString("TripDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type note.
        /// </summary>
        public static string TypeNote {
            get {
                return ResourceManager.GetString("TypeNote", resourceCulture);
            }
        }
    }
}
